client_config_backend: settings
client_config:
  client_id: 41587285103-0m3g4l0o1m9bvdd9knm0p10b8mo5evan.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install